### ISSUE TITLE
Backward compatibility?

### ISSUE THREAD

**Issue by ViBE-HU** [tiagoporsch/restartto#4]
Any plans for support recent Gnome versions? It is a must have feature. But somehow it is still not a stock Gnome thing in 2024.

**Comment by tiagoporsch** [comment]
I don't have plans to do it, as the extension API changed many times in recent GNOME versions, and in order to maintain this extension over many different shell versions it would be necessary to backport any new feature that is developed.

However if anyone wants to rewrite and maintain this extension for an older GNOME version, we could have the code in another branch and I would be happy to publish it in the GNOME Extensions website.

*EDIT*: I added support for shell-version 45 in 1302d1bd9765c87b102813d53bb5945ae206fe00, as this version still uses the same API as 46 and 47. Older versions will not be supported at this moment.

**Comment by ViBE-HU** [comment]
> I don't have plans to do it, as the extension API changed many times in recent GNOME versions, and in order to maintain this extension over many different shell versions it would be necessary to backport any new feature that is developed.
> 
> However if anyone wants to rewrite and maintain this extension for an older GNOME version, we could have the code in another branch and I would be happy to publish it in the GNOME Extensions website.
> 
> _EDIT_: I added support for shell-version 45 in [1302d1b](https://github.com/tiagoporsch/restartto/commit/1302d1bd9765c87b102813d53bb5945ae206fe00), as this version still uses the same API as 46 and 47. Older versions will not be supported at this moment.

Understand. I'm using many Ubuntu distros from 20.04, that's why I asked. It is still better than nothing. It is a pain in the @ss to that I cannot easily switch between the systems while all of my devices are dualboot for many reasons. None of the major distros care about this.
